PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL, 
	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);
CREATE TABLE players (
	id INTEGER NOT NULL, 
	_name VARCHAR(255) NOT NULL, 
	_uid VARCHAR(255) NOT NULL, 
	_password VARCHAR(255) NOT NULL, 
	_tokens INTEGER, 
	PRIMARY KEY (id), 
	UNIQUE (_uid)
);
INSERT INTO players VALUES(1,'Azeem Khan','azeemK','pbkdf2:sha256:600000$crbMSdzCho$a00c478b9b801ebbdd6cb45147625e7e6b115b7e6c96ed9ad9460fa91068aef7',45);
INSERT INTO players VALUES(2,'Ahad Biabani','ahadB','pbkdf2:sha256:600000$FTY52iKSop$ce66696419b440b8cd2a3d87eaf6cea37e88628294661c41b005ce2398674aa8',41);
INSERT INTO players VALUES(3,'Akshat Parikh','akshatP','pbkdf2:sha256:600000$079GSv5i2X$a8db5d40f7ab1980a9c8344b6e572051a87554a52cbc184ffb7e5f6ad645a546',40);
INSERT INTO players VALUES(4,'Josh Williams','joshW','pbkdf2:sha256:600000$zPAnQLlzcR$702efb5619c512519d691d3f3ea664dfc2e91265b37ba92062e76060d740bf4f',38);
INSERT INTO players VALUES(5,'John Mortensen','johnM','pbkdf2:sha256:600000$3KpNsfbpPq$84de62ca3e537c5a343e421f379228296dc2058cc9929e4b6c248d9716365c9b',35);
CREATE TABLE posts (
	id INTEGER NOT NULL, 
	note TEXT NOT NULL, 
	image VARCHAR, 
	"userID" INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY("userID") REFERENCES users (id)
);
INSERT INTO posts VALUES(1,replace('#### Thomas Edison note 0. \n Generated by test data.','\n',char(10)),'ncs_logo.png',1);
INSERT INTO posts VALUES(2,replace('#### Thomas Edison note 1. \n Generated by test data.','\n',char(10)),'ncs_logo.png',1);
INSERT INTO posts VALUES(3,replace('#### Nicholas Tesla note 0. \n Generated by test data.','\n',char(10)),'ncs_logo.png',2);
INSERT INTO posts VALUES(4,replace('#### Nicholas Tesla note 1. \n Generated by test data.','\n',char(10)),'ncs_logo.png',2);
INSERT INTO posts VALUES(5,replace('#### Alexander Graham Bell note 0. \n Generated by test data.','\n',char(10)),'ncs_logo.png',3);
INSERT INTO posts VALUES(6,replace('#### Grace Hopper note 0. \n Generated by test data.','\n',char(10)),'ncs_logo.png',4);
INSERT INTO posts VALUES(7,replace('#### Grace Hopper note 1. \n Generated by test data.','\n',char(10)),'ncs_logo.png',4);
INSERT INTO posts VALUES(8,replace('#### Grace Hopper note 2. \n Generated by test data.','\n',char(10)),'ncs_logo.png',4);
CREATE TABLE IF NOT EXISTS "users" (
	id INTEGER NOT NULL, 
	_name VARCHAR(255) NOT NULL, 
	_uid VARCHAR(255) NOT NULL, 
	_password VARCHAR(255) NOT NULL, 
	_dob DATE, _pnum TEXT, _email TEXT DEFAULT 'example@website.com', _role TEXT DEFAULT 'user', _stockmoney INTEGER, 
	PRIMARY KEY (id), 
	UNIQUE (_uid)
);
INSERT INTO users VALUES(1,'Thomas Edison','toby','pbkdf2:sha256:600000$O8TGkXyg6O$18b487daf52b62043c9221a5ea75190307ad0c53f6b66471c9f9e592476c9959','1847-02-11','123-456-7890','example@website.com','user',4100);
INSERT INTO users VALUES(2,'Nicholas Tesla','niko','pbkdf2:sha256:600000$Irjjiu7uc5$18fa5b502fb9a5f3fe465e45e4e39fc0ea50698674af7b1770f6371ca52cea72','1856-07-10','123-456-7890','example@website.com','user',5000);
INSERT INTO users VALUES(3,'Alexander Graham Bell','lex','pbkdf2:sha256:600000$ApGoNBgOR5$2f81550252532d85ec53b9c38647f7eb8e4d0b6f6aba4375473ba000c30701f4','2024-01-23','123-456-7890','example@website.com','user',5000);
INSERT INTO users VALUES(4,'Grace Hopper','hop','pbkdf2:sha256:600000$gWpinNmjRR$039016b0ede552fdb4f7775013421a852e8f5c938bf1b5f82e369811a3f15e77','1906-12-09','123-456-7890','example@website.com','user',5000);
INSERT INTO users VALUES(5,'Admin','admin','pbkdf2:sha256:600000$eH9A0x3xSS$4e239f6e79580632007c56fa3adf4bb5c958d6c5880c9f95f679a6a09369653c','2024-01-31','123-456-7890','example@website.com','admin',100);
INSERT INTO users VALUES(6,'UserABC','user','pbkdf2:sha256:600000$R8YbLnPPNc$28d712d81eae736ca8537d8b8fe9ce11e34154f81b2bef4180f9e5cdf5d7c94a','2024-02-05','false','example@website.com','user',5000);
CREATE TABLE IF NOT EXISTS "stocks_bkp" (
	id INTEGER NOT NULL, 
	_symbol VARCHAR(255) NOT NULL, 
	_company VARCHAR(255) NOT NULL, 
	_quantity VARCHAR(255) NOT NULL, _sheesh INTEGER, 
	PRIMARY KEY (id)
);
INSERT INTO stocks_bkp VALUES(1,'AAPL','Apple Inc.','5400',100);
INSERT INTO stocks_bkp VALUES(2,'MSFT','Microsoft Corp.','999',100);
INSERT INTO stocks_bkp VALUES(3,'AMZN','Amazon.com. Inc','990',100);
INSERT INTO stocks_bkp VALUES(4,'NVDA','Nvidia Corp.','1000',100);
INSERT INTO stocks_bkp VALUES(5,'GOOGL','Alphabet. Inc Class A','1000',100);
INSERT INTO stocks_bkp VALUES(6,'META','Meta Platforms Inc. Class A','1000',100);
INSERT INTO stocks_bkp VALUES(7,'TSLA','Tesla Inc.','1000',100);
INSERT INTO stocks_bkp VALUES(8,'GOOG','Alphabet Inc. Class C','1000',100);
INSERT INTO stocks_bkp VALUES(9,'BRK.B','Berkshire Hathaway Inc. Class B','1000',100);
INSERT INTO stocks_bkp VALUES(10,'AVGO','Broadcom Inc.','1000',100);
INSERT INTO stocks_bkp VALUES(11,'UNH','UnitedHealth Group Inc.','1000',100);
INSERT INTO stocks_bkp VALUES(12,'JPM','JPMorgan Chase & Co.','1000',100);
INSERT INTO stocks_bkp VALUES(13,'LLY','Eli Lilly & Co.','1000',100);
INSERT INTO stocks_bkp VALUES(14,'V','Visa Inc. Class A','1000',100);
INSERT INTO stocks_bkp VALUES(15,'XOM','Exxon Mobil Corp. ','1000',100);
INSERT INTO stocks_bkp VALUES(16,'JNJ','Johnson & Johnson','1000',100);
INSERT INTO stocks_bkp VALUES(17,'HD','Home Depot Inc.','1000',100);
INSERT INTO stocks_bkp VALUES(18,'MA','Mastercard Inc. Class A ','1000',100);
INSERT INTO stocks_bkp VALUES(19,'PG','Procter & Gamble Co.','1000',100);
INSERT INTO stocks_bkp VALUES(20,'COST','Costco Wholesale Corp.','1000',100);
INSERT INTO stocks_bkp VALUES(21,'ABBV','AbbVie Inc.','1000',100);
INSERT INTO stocks_bkp VALUES(22,'MRK','Merck & Co. Inc.','1000',100);
INSERT INTO stocks_bkp VALUES(23,'ADBE','Adobe Inc.','1000',100);
INSERT INTO stocks_bkp VALUES(24,'CVX','Chevron Corp. ','1000',100);
INSERT INTO stocks_bkp VALUES(25,'CRM','Salesforce Inc.','1000',100);
CREATE TABLE transactions (
	id INTEGER NOT NULL, 
	_uid VARCHAR(255) NOT NULL, 
	_symbol VARCHAR(255) NOT NULL, 
	_transaction_type VARCHAR(255) NOT NULL, 
	_quantity VARCHAR(255) NOT NULL, 
	_transaction_amount INTEGER NOT NULL, 
	_transaction_date DATE, 
	PRIMARY KEY (id), 
	UNIQUE (_uid)
);
INSERT INTO transactions VALUES(1,'toby','AAPL','buy','1',100,NULL);
INSERT INTO transactions VALUES(2,'admin','AAPL','buy','11',1100,NULL);
CREATE TABLE IF NOT EXISTS "stocks" (
	id INTEGER NOT NULL, 
	_symbol VARCHAR(255) NOT NULL, 
	_company VARCHAR(255) NOT NULL, 
	_quantity INTEGER NOT NULL, _sheesh INTEGER, 
	PRIMARY KEY (id)
);
INSERT INTO stocks VALUES(1,'AAPL','Apple Inc.',489,100);
INSERT INTO stocks VALUES(2,'MSFT','Microsoft Corp.',999,100);
INSERT INTO stocks VALUES(3,'AMZN','Amazon.com. Inc',990,100);
INSERT INTO stocks VALUES(4,'NVDA','Nvidia Corp.',1000,100);
INSERT INTO stocks VALUES(5,'GOOGL','Alphabet. Inc Class A',1000,100);
INSERT INTO stocks VALUES(6,'META','Meta Platforms Inc. Class A',989,100);
INSERT INTO stocks VALUES(7,'TSLA','Tesla Inc.',1000,100);
INSERT INTO stocks VALUES(8,'GOOG','Alphabet Inc. Class C',1000,100);
INSERT INTO stocks VALUES(9,'BRK.B','Berkshire Hathaway Inc. Class B',1000,100);
INSERT INTO stocks VALUES(10,'AVGO','Broadcom Inc.',1000,100);
INSERT INTO stocks VALUES(11,'UNH','UnitedHealth Group Inc.',1000,100);
INSERT INTO stocks VALUES(12,'JPM','JPMorgan Chase & Co.',1000,100);
INSERT INTO stocks VALUES(13,'LLY','Eli Lilly & Co.',1000,100);
INSERT INTO stocks VALUES(14,'V','Visa Inc. Class A',1000,100);
INSERT INTO stocks VALUES(15,'XOM','Exxon Mobil Corp. ',1000,100);
INSERT INTO stocks VALUES(16,'JNJ','Johnson & Johnson',1000,100);
INSERT INTO stocks VALUES(17,'HD','Home Depot Inc.',1000,100);
INSERT INTO stocks VALUES(18,'MA','Mastercard Inc. Class A ',1000,100);
INSERT INTO stocks VALUES(19,'PG','Procter & Gamble Co.',1000,100);
INSERT INTO stocks VALUES(20,'COST','Costco Wholesale Corp.',1000,100);
INSERT INTO stocks VALUES(21,'ABBV','AbbVie Inc.',1000,100);
INSERT INTO stocks VALUES(22,'MRK','Merck & Co. Inc.',1000,100);
INSERT INTO stocks VALUES(23,'ADBE','Adobe Inc.',1000,100);
INSERT INTO stocks VALUES(24,'CVX','Chevron Corp. ',1000,100);
INSERT INTO stocks VALUES(25,'CRM','Salesforce Inc.',1000,100);
COMMIT;
